%% Licensed to the Apache Software Foundation (ASF) under one
%% or more contributor license agreements.  See the NOTICE file
%% distributed with this work for additional information
%% regarding copyright ownership.  The ASF licenses this file
%% to you under the Apache License, Version 2.0 (the
%% "License"); you may not use this file except in compliance
%% with the License.  You may obtain a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.

flowchart TD
    B["🤖 GitHub Workflow<br/>🔧 Manual trigger from release manager<br/><br/>• Create a new branch from the Git SHA<br/>• Push the branch to the remote repository"]

    B --> C["👤 Release Manager<br/><br/>• Cherry pick the commits from main branch to release branch<br/>• Ensure that the changelog is up to date<br/>• Create a pull request to add the commits<br/>• Get the pull request approved and merged"]

    C --> D["🤖 GitHub Workflow<br/>🔧 Manual trigger from release manager<br/><br/>• Verify that all Github checks are passing<br/>• Update the project version files<br/>• Finalize the changelog for the release<br/>• Commit the changes to release branch<br/>• Create the RC tag<br/>• Push the branch and the tag"]

    D --> E["🤖 GitHub Workflow<br/>🔧 Manual trigger from release manager<br/>• Build the source and binary artifacts<br/>• Stage artifacts to dist dev repository<br/>• Publish artifacts to Nexus staging repository<br/>• Close Nexus staging repository<br/>• Build Docker images for server and admin tool<br/>• Build the Helm chart<br/>• Create signature and checksum for Helm package files<br/>• Copy package files to dist dev repository"]

    E --> H["👤 Release Manager<br/><br/>• Start vote thread on dev mailing list<br/>• Wait for the vote to pass"]

    H --> I["🤖 GitHub Workflow<br/>🔧 Manual trigger from release manager<br/><br/>• Create a final release tag to Git repository<br/>• Create the GitHub release (artifacts downloaded from dist dev)<br/>• Publish Docker images to DockerHub<br/>• Release the candidate repository on Nexus"]

    I --> L["👤 Release Manager<br/><br/>• svn mv distribution, Helm chart, and Python client from dist dev to dist release<br/>• svn mv Helm index.yaml and artifacthub-repo.yml from dist dev to dist release<br/>• svn rm old release versions superseded by this release"]

    L --> J["👤 Release Manager<br/><br/>• Update documentation - TBD - Process yet to be determined"]

    L --> K["👤 Release Manager<br/><br/>• Send announcement e-mail to dev mailing list<br/>• Send announcement to announce Apache mailing list"]

    %% Class definition for left-aligned text
    classDef leftAlign text-align:left;

    %% Apply left-align class to all nodes
    class B,C,D,E,H,I,J,K,L leftAlign;
