# coding: utf-8

"""
    Polaris Management Service

    Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TablePrivilege(str, Enum):
    """
    TablePrivilege
    """

    """
    allowed enum values
    """
    CATALOG_MANAGE_ACCESS = 'CATALOG_MANAGE_ACCESS'
    TABLE_DROP = 'TABLE_DROP'
    TABLE_LIST = 'TABLE_LIST'
    TABLE_READ_PROPERTIES = 'TABLE_READ_PROPERTIES'
    VIEW_READ_PROPERTIES = 'VIEW_READ_PROPERTIES'
    TABLE_WRITE_PROPERTIES = 'TABLE_WRITE_PROPERTIES'
    TABLE_READ_DATA = 'TABLE_READ_DATA'
    TABLE_WRITE_DATA = 'TABLE_WRITE_DATA'
    TABLE_FULL_METADATA = 'TABLE_FULL_METADATA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TablePrivilege from a JSON string"""
        return cls(json.loads(json_str))


