# coding: utf-8

"""
    Polaris Management Service

    Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ViewPrivilege(str, Enum):
    """
    ViewPrivilege
    """

    """
    allowed enum values
    """
    CATALOG_MANAGE_ACCESS = 'CATALOG_MANAGE_ACCESS'
    VIEW_CREATE = 'VIEW_CREATE'
    VIEW_DROP = 'VIEW_DROP'
    VIEW_LIST = 'VIEW_LIST'
    VIEW_READ_PROPERTIES = 'VIEW_READ_PROPERTIES'
    VIEW_WRITE_PROPERTIES = 'VIEW_WRITE_PROPERTIES'
    VIEW_FULL_METADATA = 'VIEW_FULL_METADATA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ViewPrivilege from a JSON string"""
        return cls(json.loads(json_str))


