openapi: "3.0.3"
info:
  title: "GSAll API"
  description: "GSAll API"
  version: "1.0.0"
servers:
  - url: "https://snowflake.dev.local:8080/"
paths:
  /api/polaris/oauth/tokens:
    post:
      summary: "POST api/polaris/oauth/tokens"
      operationId: "getToken"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string