#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

services:
  polaris-1:
    image: apache/polaris:postgres-latest
    depends_on:
      polaris-bootstrap:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      JAVA_DEBUG: "true"
      JAVA_DEBUG_PORT: "*:5005"
      JAVA_OPTS: "-Dsuspend -Ddebug -XX:+UseParallelGC -Xms1G -Xmx1G -XX:+AlwaysPreTouch -Xlog:gc*=debug,safepoint*:file=/tmp/gc.log:uptime,tags,level:filecount=1,filesize=200M"
      polaris.persistence.type: eclipse-link
      polaris.persistence.eclipselink.configuration-file: /deployments/config/eclipselink/persistence.xml
      polaris.realm-context.realms: POLARIS
      polaris.authentication.token-broker.type: symmetric-key
      polaris.authentication.token-broker.symmetric-key.secret: THE_VERY_SECRET_KEY
      quarkus.otel.sdk.disabled: "true"
    volumes:
      - ../assets/eclipselink/:/deployments/config/eclipselink
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10

  polaris-2:
    image: apache/polaris:postgres-latest
    depends_on:
      polaris-bootstrap:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      JAVA_DEBUG: "true"
      JAVA_DEBUG_PORT: "*:5006"  # Changed debug port
      JAVA_OPTS: "-Dsuspend -Ddebug -XX:+UseParallelGC -Xms1G -Xmx1G -XX:+AlwaysPreTouch -Xlog:gc*=debug,safepoint*:file=/tmp/gc.log:uptime,tags,level:filecount=1,filesize=200M"
      polaris.persistence.type: eclipse-link
      polaris.persistence.eclipselink.configuration-file: /deployments/config/eclipselink/persistence.xml
      polaris.realm-context.realms: POLARIS
      polaris.authentication.token-broker.type: symmetric-key
      polaris.authentication.token-broker.symmetric-key.secret: THE_VERY_SECRET_KEY
      quarkus.otel.sdk.disabled: "true"
    volumes:
      - ../assets/eclipselink/:/deployments/config/eclipselink
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10

  polaris-3:
    image: apache/polaris:postgres-latest
    depends_on:
      polaris-bootstrap:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      JAVA_DEBUG: "true"
      JAVA_DEBUG_PORT: "*:5007"  # Changed debug port
      JAVA_OPTS: "-Dsuspend -Ddebug -XX:+UseParallelGC -Xms1G -Xmx1G -XX:+AlwaysPreTouch -Xlog:gc*=debug,safepoint*:file=/tmp/gc.log:uptime,tags,level:filecount=1,filesize=200M"
      polaris.persistence.type: eclipse-link
      polaris.persistence.eclipselink.configuration-file: /deployments/config/eclipselink/persistence.xml
      polaris.realm-context.realms: POLARIS
      polaris.authentication.token-broker.type: symmetric-key
      polaris.authentication.token-broker.symmetric-key.secret: THE_VERY_SECRET_KEY
      quarkus.otel.sdk.disabled: "true"
    volumes:
      - ../assets/eclipselink/:/deployments/config/eclipselink
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10

  polaris:
    image: nginx:latest
    ports:
      - "8181:8181"  # Expose on port 8181
    depends_on:
      - polaris-1
      - polaris-2
      - polaris-3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

  polaris-bootstrap:
    # IMPORTANT: the image MUST contain the Postgres JDBC driver and EclipseLink dependencies, see README for instructions
    image: apache/polaris-admin-tool:postgres-latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      polaris.persistence.type: eclipse-link
      polaris.persistence.eclipselink.configuration-file: /deployments/config/eclipselink/persistence.xml
    volumes:
      - ../assets/eclipselink/:/deployments/config/eclipselink
    command:
      - "bootstrap"
      - "--realm=POLARIS"
      - "--credential=POLARIS,root,s3cr3t"

  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POLARIS
      POSTGRES_INITDB_ARGS: "--encoding UTF8 --data-checksums"
    volumes:
      # Bind local conf file to a convenient location in the container
      - type: bind
        source: ./postgresql.conf
        target: /etc/postgresql/postgresql.conf
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 2s
      retries: 15
