#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
 
# The format of this file is documented at
# https://github.com/apache/infrastructure-asfyaml
# also at
# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

github:
  description: "Apache Polaris, the interoperable, open source catalog for Apache Iceberg"
  homepage: https://polaris.apache.org/
  labels:
    - polaris
    - iceberg
    - apache

  enabled_merge_buttons:
    merge: true
    squash: true
    rebase: true

  protected_branches:
    main:
      required_pull_request_reviews:
        require_code_owner_reviews: false
        required_approving_review_count: 1

      required_linear_history: true

      del_branch_on_merge: true

      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # Contexts are the names of checks that must pass. This is the value
        # of the job's `name` property if it's present.
        contexts:
          - markdown-link-check
          - build
          - regtest
          - site
          - "Helm tests"

  features:
    wiki: false
    issues: true
    projects: true
  ghp_branch: gh-pages
  ghp_path: /

notifications:
  commits:      commits@polaris.apache.org
  issues:       issues@polaris.apache.org
  pullrequests: issues@polaris.apache.org
  jira_options: link label

publish:
  whoami: asf-site
