#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

set -e

dir=${0%/*}

if [ ! -d "${dir}"/polaris-venv ]; then
  echo "Performing first-time setup for the Python client..."
  rm -f "${dir}"/poetry.lock
  python3 -m venv "${dir}"/polaris-venv
  . "${dir}"/polaris-venv/bin/activate
  pip install -r regtests/requirements.txt
  pip install pydantic python-dateutil

  cp "${dir}"/client/python/pyproject.toml "${dir}"
  pushd "$dir" && poetry install ; popd

  deactivate
  echo "First time setup complete."
fi

cd "$dir"
env PYTHONPATH=client/python SCRIPT_DIR="$dir" "${dir}"/polaris-venv/bin/python3 client/python/cli/polaris_cli.py "$@"
