#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
import os
from enum import Enum


class StorageType(Enum):
    """
    Represents a Storage Type within the Polaris API -- `s3`, `azure`, `gcs`, or `file`.
    """

    S3 = "s3"
    AZURE = "azure"
    GCS = "gcs"
    FILE = "file"


class CatalogType(Enum):
    """
    Represents a Catalog Type within the Polaris API -- `internal` or `external`
    """

    INTERNAL = "internal"
    EXTERNAL = "external"


class PrincipalType(Enum):
    """
    Represents a Principal Type within the Polaris API -- currently only `service`
    """

    SERVICE = "service"


class CatalogConnectionType(Enum):
    """
    Represents a ConnectionType for an EXTERNAL catalog -- see ConnectionConfigInfo in the spec
    """

    HADOOP = "hadoop"
    ICEBERG = "iceberg-rest"
    HIVE = "hive"


class AuthenticationType(Enum):
    """
    Represents a AuthenticationType for an EXTERNAL catalog -- see AuthenticationParameters in the spec
    """

    OAUTH = "oauth"
    BEARER = "bearer"
    SIGV4 = "sigv4"
    IMPLICIT = "implicit"


class ServiceIdentityType(Enum):
    """
    Represents a Service Identity Type for an EXTERNAL catalog -- see ServiceIdentityInfo in the spec
    """

    AWS_IAM = "aws_iam"


class EntityType(Enum):
    """
    Represents the type of entities that can be searched or managed in the CLI
    """

    CATALOG = "catalog"
    CATALOG_ROLE = "catalog-role"
    NAMESPACE = "namespace"
    PRINCIPAL = "principal"
    PRINCIPAL_ROLE = "principal-role"
    TABLE = "table"
    VIEW = "view"

    def __str__(self) -> str:
        # Transforms 'catalog-role' tp 'Catalog Role'
        return self.value.replace("-", " ").title()


class Commands:
    """
    Represents the various commands available in the CLI
    """

    CATALOGS = "catalogs"
    PRINCIPALS = "principals"
    PRINCIPAL_ROLES = "principal-roles"
    CATALOG_ROLES = "catalog-roles"
    PRIVILEGES = "privileges"
    NAMESPACES = "namespaces"
    PROFILES = "profiles"
    POLICIES = "policies"
    SETUP = "setup"
    TABLES = "tables"
    FIND = "find"


class Subcommands:
    """
    Represents the various subcommands available in the CLI. This is a flattened view, and no one command supports
    all these subcommands.
    """

    CREATE = "create"
    DELETE = "delete"
    GET = "get"
    LIST = "list"
    UPDATE = "update"
    ROTATE_CREDENTIALS = "rotate-credentials"
    CATALOG = "catalog"
    NAMESPACE = "namespace"
    TABLE = "table"
    VIEW = "view"
    GRANT = "grant"
    REVOKE = "revoke"
    ACCESS = "access"
    RESET = "reset"
    ATTACH = "attach"
    DETACH = "detach"
    APPLY = "apply"
    EXPORT = "export"
    SUMMARIZE = "summarize"


class Actions:
    """
    Represents actions available to different subcommands available in the CLI. Currently, only some subcommands of the
    `privileges` command support actions.
    """

    GRANT = "grant"
    REVOKE = "revoke"


class Arguments:
    """
    Constants to represent different arguments used by various commands. This is a flattened view, and no one
    subcommand supports all these arguments. These argument names map directly to the parameters that the CLI expects
    and to the attribute names within the argparse Namespace generated by parsing.

    These values should be snake_case, but they will get mapped to kebab-case in `Parser.parse`
    """

    TYPE = "type"
    DEFAULT_BASE_LOCATION = "default_base_location"
    STORAGE_TYPE = "storage_type"
    ALLOWED_LOCATION = "allowed_location"
    ROLE_ARN = "role_arn"
    EXTERNAL_ID = "external_id"
    USER_ARN = "user_arn"
    TENANT_ID = "tenant_id"
    MULTI_TENANT_APP_NAME = "multi_tenant_app_name"
    HIERARCHICAL = "hierarchical"
    CONSENT_URL = "consent_url"
    SERVICE_ACCOUNT = "service_account"
    CATALOG_ROLE = "catalog_role"
    CATALOG = "catalog"
    PRINCIPAL = "principal"
    CLIENT_ID = "client_id"
    PRINCIPAL_ROLE = "principal_role"
    PROPERTY = "property"
    SET_PROPERTY = "set_property"
    REMOVE_PROPERTY = "remove_property"
    PRIVILEGE = "privilege"
    NAMESPACE = "namespace"
    TABLE = "table"
    VIEW = "view"
    CASCADE = "cascade"
    CLIENT_SECRET = "client_secret"
    NEW_CLIENT_ID = "new_client_id"
    NEW_CLIENT_SECRET = "new_client_secret"
    ACCESS_TOKEN = "access_token"
    HOST = "host"
    PORT = "port"
    BASE_URL = "base_url"
    PARENT = "parent"
    LOCATION = "location"
    REGION = "region"
    PROFILE = "profile"
    PROXY = "proxy"
    DEBUG = "debug"
    HADOOP_WAREHOUSE = "hadoop_warehouse"
    HIVE_WAREHOUSE = "hive_warehouse"
    ICEBERG_REMOTE_CATALOG_NAME = "iceberg_remote_catalog_name"
    ENDPOINT = "endpoint"
    ENDPOINT_INTERNAL = "endpoint_internal"
    STS_ENDPOINT = "sts_endpoint"
    STS_UNAVAILABLE = "no_sts"
    KMS_UNAVAILABLE = "no_kms"
    KMS_KEY_CURRENT = "current_kms_key"
    KMS_KEY_ALLOWED = "allowed_kms_key"
    PATH_STYLE_ACCESS = "path_style_access"
    CATALOG_CONNECTION_TYPE = "catalog_connection_type"
    CATALOG_AUTHENTICATION_TYPE = "catalog_authentication_type"
    CATALOG_SERVICE_IDENTITY_TYPE = "catalog_service_identity_type"
    CATALOG_SERVICE_IDENTITY_IAM_ARN = "catalog_service_identity_iam_arn"
    CATALOG_URI = "catalog_uri"
    CATALOG_TOKEN_URI = "catalog_token_uri"
    CATALOG_CLIENT_ID = "catalog_client_id"
    CATALOG_CLIENT_SECRET = "catalog_client_secret"
    CATALOG_CLIENT_SCOPE = "catalog_client_scope"
    CATALOG_BEARER_TOKEN = "catalog_bearer_token"
    CATALOG_ROLE_ARN = "catalog_role_arn"
    CATALOG_ROLE_SESSION_NAME = "catalog_role_session_name"
    CATALOG_EXTERNAL_ID = "catalog_external_id"
    CATALOG_SIGNING_REGION = "catalog_signing_region"
    CATALOG_SIGNING_NAME = "catalog_signing_name"
    POLICY = "policy"
    POLICY_FILE = "policy_file"
    POLICY_TYPE = "policy_type"
    POLICY_DESCRIPTION = "policy_description"
    TARGET_NAME = "target_name"
    PARAMETERS = "parameters"
    DETACH_ALL = "detach_all"
    APPLICABLE = "applicable"
    ATTACHMENT_TYPE = "attachment_type"
    ATTACHMENT_PATH = "attachment_path"
    SETUP_CONFIG = "setup_config"
    DRY_RUN = "dry_run"
    REALM = "realm"
    HEADER = "header"
    IDENTIFIER = "identifier"


class Hints:
    """
    Constants used as hints by the various --help outputs.
    """

    PROPERTY = (
        "A key/value pair such as: tag=value. Multiple can be provided by specifying this option"
        " more than once"
    )
    SET_PROPERTY = (
        "A key/value pair such as: tag=value. Merges the specified key/value into an existing"
        " properties map by updating the value if the key already exists or creating a new"
        " entry if not. Multiple can be provided by specifying this option more than once"
    )
    REMOVE_PROPERTY = (
        "A key to remove from a properties map. If the key already does not exist then"
        " no action is taken for the specified key. Multiple can be provided by specifying"
        " this option more than once"
    )

    # Entities Hints
    CATALOG = "The name of a catalog"
    CATALOG_ROLE = "The name of a catalog role"
    PRINCIPAL = "The name of a principal"
    PRINCIPAL_ROLE = "The name of a principal role"
    NAMESPACE = "A period-delimited namespace"
    TABLE = "The name of a table"
    VIEW = "The name of a view"

    # Storage Hints
    ## S3
    S3_ROLE_ARN = "A role ARN to use when connecting to S3"
    S3_EXTERNAL_ID = "The external ID to use when connecting to S3"
    S3_REGION = "The region to use when connecting to S3"
    S3_USER_ARN = "A user ARN to use when connecting to S3"
    S3_ENDPOINT = "The S3 endpoint to use when connecting to S3"
    S3_ENDPOINT_INTERNAL = "The S3 endpoint used by Polaris to use when connecting to S3, if different from the one that clients use"
    S3_STS_ENDPOINT = "The STS endpoint to use when connecting to STS"
    S3_STS_UNAVAILABLE = (
        "Indicates that Polaris should not use STS (e.g. if STS is not available)"
    )
    S3_KMS_UNAVAILABLE = (
        "Indicates that Polaris should not use KMS (e.g. if KMS is not available)"
    )
    S3_PATH_STYLE_ACCESS = "Whether to use path-style-access for S3"
    S3_KMS_KEY_CURRENT = "The AWS KMS key ARN to be used for encrypting new S3 data"
    S3_KMS_KEY_ALLOWED = "AWS KMS key ARN(s) that this catalog and its clients are allowed to use for reading S3 data (zero or more)"
    ## Azure
    AZURE_TENANT_ID = "(Required) A tenant ID to use when connecting to Azure Storage"
    AZURE_MULTI_TENANT_APP_NAME = "The app name to use when connecting to Azure Storage"
    AZURE_HIERARCHICAL = "Indicates whether the referenced Azure storage location(s) support hierarchical namespaces"
    AZURE_CONSENT_URL = (
        "A consent URL granting permissions for the Azure Storage location"
    )
    ## GCP
    GCS_SERVICE_ACCOUNT = "The service account to use when connecting to GCS"

    # Federation Hints
    EXTERNAL_CATALOG_URI = "The URI of the external catalog"
    HADOOP_WAREHOUSE = "The warehouse to use when federating to a HADOOP catalog"
    HIVE_WAREHOUSE = "The warehouse to use when federating to a HIVE catalog"
    ICEBERG_REMOTE_CATALOG_NAME = (
        "The remote catalog name when federating to an Iceberg REST catalog"
    )
    ## OAuth
    OAUTH_TOKEN_URI = "Token server URI"
    OAUTH_CLIENT_ID = "OAuth client ID"
    OAUTH_CLIENT_SECRET = "OAuth client secret (input-only)"
    OAUTH_CLIENT_SCOPE = (
        "OAuth scopes to specify when exchanging for a short-lived access token. "
        "Multiple can be provided by specifying this option more than once"
    )
    ## Bearer
    BEARER_TOKEN = "Bearer token (input-only)"
    ## SigV4
    SIGV4_ROLE_ARN = "The AWS IAM role ARN assumed by Polaris when signing requests"
    SIGV4_ROLE_SESSION_NAME = (
        "The role session name to be used by the SigV4 protocol for signing requests"
    )
    SIGV4_EXTERNAL_ID = (
        "An optional external ID used to establish a AWS trust relationship"
    )
    SIGV4_SIGNING_REGION = (
        "Region to be used by the SigV4 protocol for signing requests"
    )
    SIGV4_SIGNING_NAME = (
        "The service name to be used by the SigV4 protocol for signing requests"
    )

    # AWS IAM Identity Options
    AWS_IAM_ARN = (
        "The ARN of the IAM user or IAM role Polaris uses to assume roles and "
        "then access external resources."
    )


UNIT_SEPARATOR = chr(0x1F)
CLIENT_ID_ENV = "CLIENT_ID"
CLIENT_SECRET_ENV = "CLIENT_SECRET"
CLIENT_PROFILE_ENV = "CLIENT_PROFILE"
REALM_ENV = "REALM"
HEADER_ENV = "HEADER"
DEFAULT_HEADER = "Polaris-Realm"
DEFAULT_HOSTNAME = "localhost"
DEFAULT_PORT = 8181
CONFIG_DIR = (os.environ.get("POLARIS_HOME") or "").strip() or os.path.expanduser(
    "~/.polaris"
)
CONFIG_FILE = os.path.join(CONFIG_DIR, ".polaris.json")
