#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#

polaris-bom=bom
polaris-core=polaris-core
polaris-api-iceberg-service=api/iceberg-service
polaris-api-management-model=api/management-model
polaris-api-management-service=api/management-service
polaris-api-catalog-service=api/polaris-catalog-service
polaris-service-common=service/common
polaris-quarkus-defaults=quarkus/defaults
polaris-quarkus-service=quarkus/service
polaris-quarkus-server=quarkus/server
polaris-quarkus-spark-tests=quarkus/spark-tests
polaris-quarkus-admin=quarkus/admin
polaris-quarkus-run-script=quarkus/run-script
polaris-eclipselink=extension/persistence/eclipselink
polaris-jpa-model=extension/persistence/jpa-model
polaris-tests=integration-tests
aggregated-license-report=aggregated-license-report
polaris-immutables=tools/immutables
polaris-container-spec-helper=tools/container-spec-helper
polaris-version=tools/version
polaris-misc-types=tools/misc-types
polaris-persistence-varint=components/persistence/varint

polaris-config-docs-annotations=tools/config-docs/annotations
polaris-config-docs-generator=tools/config-docs/generator
polaris-config-docs-site=tools/config-docs/site

# executor abstraction
polaris-async-api=components/async/api
polaris-async-java=components/async/java
polaris-async-vertx=components/async/vertx

# id generation
polaris-idgen-api=components/idgen/api
polaris-idgen-impl=components/idgen/impl
polaris-idgen-mocks=components/idgen/mocks
polaris-idgen-spi=components/idgen/spi

# nodes
polaris-nodes-api=components/nodes/api
polaris-nodes-impl=components/nodes/impl
polaris-nodes-spi=components/nodes/spi
polaris-nodes-store=components/nodes/store

# realms
polaris-realms-api=components/realms/api
polaris-realms-impl=components/realms/impl
polaris-realms-spi=components/realms/spi
polaris-realms-store=components/realms/store

# authz
polaris-authz-api=components/authz/api
polaris-authz-impl=components/authz/impl
polaris-authz-spi=components/authz/spi
polaris-authz-store=components/authz/store

# persistence / database agnostic
polaris-persistence-api=components/persistence/api
polaris-persistence-impl=components/persistence/impl
polaris-persistence-benchmark=components/persistence/benchmark
polaris-persistence-bridge=components/persistence/bridge
polaris-persistence-cache=components/persistence/cache
polaris-persistence-cdi-common=components/persistence/cdi/common
polaris-persistence-cdi-quarkus=components/persistence/cdi/quarkus
polaris-persistence-cdi-weld=components/persistence/cdi/weld
polaris-persistence-commits=components/persistence/commits
polaris-persistence-correctness=components/persistence/correctness
polaris-persistence-delegate=components/persistence/delegate
polaris-persistence-index=components/persistence/index
polaris-persistence-standalone=components/persistence/standalone
polaris-persistence-testextension=components/persistence/testextension
polaris-persistence-types=components/persistence/types

# persistence / database specific implementations
polaris-persistence-inmemory=components/persistence/db/inmemory
polaris-persistence-mongodb=components/persistence/db/mongodb
