/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.polaris.service.events;

public enum PolarisEventType {
  // Catalog Events
  BEFORE_CREATE_CATALOG,
  AFTER_CREATE_CATALOG,
  BEFORE_DELETE_CATALOG,
  AFTER_DELETE_CATALOG,
  BEFORE_GET_CATALOG,
  AFTER_GET_CATALOG,
  BEFORE_UPDATE_CATALOG,
  AFTER_UPDATE_CATALOG,
  BEFORE_LIST_CATALOGS,
  AFTER_LIST_CATALOGS,

  // Catalog Role Events
  BEFORE_CREATE_CATALOG_ROLE,
  AFTER_CREATE_CATALOG_ROLE,
  BEFORE_DELETE_CATALOG_ROLE,
  AFTER_DELETE_CATALOG_ROLE,
  BEFORE_GET_CATALOG_ROLE,
  AFTER_GET_CATALOG_ROLE,
  BEFORE_UPDATE_CATALOG_ROLE,
  AFTER_UPDATE_CATALOG_ROLE,
  BEFORE_LIST_CATALOG_ROLES,
  AFTER_LIST_CATALOG_ROLES,
  BEFORE_ADD_GRANT_TO_CATALOG_ROLE,
  AFTER_ADD_GRANT_TO_CATALOG_ROLE,
  BEFORE_REVOKE_GRANT_FROM_CATALOG_ROLE,
  AFTER_REVOKE_GRANT_FROM_CATALOG_ROLE,
  BEFORE_LIST_ASSIGNEE_PRINCIPAL_ROLES_FOR_CATALOG_ROLE,
  AFTER_LIST_ASSIGNEE_PRINCIPAL_ROLES_FOR_CATALOG_ROLE,
  BEFORE_LIST_GRANTS_FOR_CATALOG_ROLE,
  AFTER_LIST_GRANTS_FOR_CATALOG_ROLE,

  // Principal Events
  BEFORE_CREATE_PRINCIPAL,
  AFTER_CREATE_PRINCIPAL,
  BEFORE_DELETE_PRINCIPAL,
  AFTER_DELETE_PRINCIPAL,
  BEFORE_GET_PRINCIPAL,
  AFTER_GET_PRINCIPAL,
  BEFORE_UPDATE_PRINCIPAL,
  AFTER_UPDATE_PRINCIPAL,
  BEFORE_ROTATE_CREDENTIALS,
  AFTER_ROTATE_CREDENTIALS,
  BEFORE_RESET_CREDENTIALS,
  AFTER_RESET_CREDENTIALS,
  BEFORE_LIST_PRINCIPALS,
  AFTER_LIST_PRINCIPALS,
  BEFORE_ASSIGN_PRINCIPAL_ROLE,
  AFTER_ASSIGN_PRINCIPAL_ROLE,
  BEFORE_REVOKE_PRINCIPAL_ROLE,
  AFTER_REVOKE_PRINCIPAL_ROLE,
  BEFORE_LIST_ASSIGNED_PRINCIPAL_ROLES,
  AFTER_LIST_ASSIGNED_PRINCIPAL_ROLES,

  // Principal Role Events
  BEFORE_CREATE_PRINCIPAL_ROLE,
  AFTER_CREATE_PRINCIPAL_ROLE,
  BEFORE_DELETE_PRINCIPAL_ROLE,
  AFTER_DELETE_PRINCIPAL_ROLE,
  BEFORE_GET_PRINCIPAL_ROLE,
  AFTER_GET_PRINCIPAL_ROLE,
  BEFORE_UPDATE_PRINCIPAL_ROLE,
  AFTER_UPDATE_PRINCIPAL_ROLE,
  BEFORE_LIST_PRINCIPAL_ROLES,
  AFTER_LIST_PRINCIPAL_ROLES,
  BEFORE_ASSIGN_CATALOG_ROLE_TO_PRINCIPAL_ROLE,
  AFTER_ASSIGN_CATALOG_ROLE_TO_PRINCIPAL_ROLE,
  BEFORE_REVOKE_CATALOG_ROLE_FROM_PRINCIPAL_ROLE,
  AFTER_REVOKE_CATALOG_ROLE_FROM_PRINCIPAL_ROLE,
  BEFORE_LIST_ASSIGNEE_PRINCIPALS_FOR_PRINCIPAL_ROLE,
  AFTER_LIST_ASSIGNEE_PRINCIPALS_FOR_PRINCIPAL_ROLE,
  BEFORE_LIST_CATALOG_ROLES_FOR_PRINCIPAL_ROLE,
  AFTER_LIST_CATALOG_ROLES_FOR_PRINCIPAL_ROLE,

  // Namespace Events
  BEFORE_CREATE_NAMESPACE,
  AFTER_CREATE_NAMESPACE,
  BEFORE_LIST_NAMESPACES,
  AFTER_LIST_NAMESPACES,
  BEFORE_LOAD_NAMESPACE_METADATA,
  AFTER_LOAD_NAMESPACE_METADATA,
  BEFORE_CHECK_EXISTS_NAMESPACE,
  AFTER_CHECK_EXISTS_NAMESPACE,
  BEFORE_DROP_NAMESPACE,
  AFTER_DROP_NAMESPACE,
  BEFORE_UPDATE_NAMESPACE_PROPERTIES,
  AFTER_UPDATE_NAMESPACE_PROPERTIES,

  // Table Events
  BEFORE_CREATE_TABLE,
  AFTER_CREATE_TABLE,
  BEFORE_LIST_TABLES,
  AFTER_LIST_TABLES,
  BEFORE_LOAD_TABLE,
  AFTER_LOAD_TABLE,
  BEFORE_CHECK_EXISTS_TABLE,
  AFTER_CHECK_EXISTS_TABLE,
  BEFORE_DROP_TABLE,
  AFTER_DROP_TABLE,
  BEFORE_REGISTER_TABLE,
  AFTER_REGISTER_TABLE,
  BEFORE_RENAME_TABLE,
  AFTER_RENAME_TABLE,
  BEFORE_UPDATE_TABLE,
  AFTER_UPDATE_TABLE,
  BEFORE_COMMIT_TABLE, // REMOVED FROM SOURCE CODE
  AFTER_COMMIT_TABLE, // REMOVED FROM SOURCE CODE
  BEFORE_REFRESH_TABLE,
  AFTER_REFRESH_TABLE,

  // View Events
  BEFORE_CREATE_VIEW,
  AFTER_CREATE_VIEW,
  BEFORE_LIST_VIEWS,
  AFTER_LIST_VIEWS,
  BEFORE_LOAD_VIEW,
  AFTER_LOAD_VIEW,
  BEFORE_CHECK_EXISTS_VIEW,
  AFTER_CHECK_EXISTS_VIEW,
  BEFORE_DROP_VIEW,
  AFTER_DROP_VIEW,
  BEFORE_RENAME_VIEW,
  AFTER_RENAME_VIEW,
  BEFORE_REPLACE_VIEW,
  AFTER_REPLACE_VIEW,
  BEFORE_COMMIT_VIEW,
  AFTER_COMMIT_VIEW,
  BEFORE_REFRESH_VIEW,
  AFTER_REFRESH_VIEW,

  // Credential Events
  BEFORE_LOAD_CREDENTIALS,
  AFTER_LOAD_CREDENTIALS,

  // Transaction Events
  BEFORE_COMMIT_TRANSACTION,
  AFTER_COMMIT_TRANSACTION,

  // Notification Events
  BEFORE_SEND_NOTIFICATION,
  AFTER_SEND_NOTIFICATION,

  // Configuration Events
  BEFORE_GET_CONFIG,
  AFTER_GET_CONFIG,

  // Policy Events
  BEFORE_CREATE_POLICY,
  AFTER_CREATE_POLICY,
  BEFORE_LIST_POLICIES,
  AFTER_LIST_POLICIES,
  BEFORE_LOAD_POLICY,
  AFTER_LOAD_POLICY,
  BEFORE_UPDATE_POLICY,
  AFTER_UPDATE_POLICY,
  BEFORE_DROP_POLICY,
  AFTER_DROP_POLICY,
  BEFORE_ATTACH_POLICY,
  AFTER_ATTACH_POLICY,
  BEFORE_DETACH_POLICY,
  AFTER_DETACH_POLICY,
  BEFORE_GET_APPLICABLE_POLICIES,
  AFTER_GET_APPLICABLE_POLICIES,

  // Generic Table Events
  BEFORE_CREATE_GENERIC_TABLE,
  AFTER_CREATE_GENERIC_TABLE,
  BEFORE_DROP_GENERIC_TABLE,
  AFTER_DROP_GENERIC_TABLE,
  BEFORE_LIST_GENERIC_TABLES,
  AFTER_LIST_GENERIC_TABLES,
  BEFORE_LOAD_GENERIC_TABLE,
  AFTER_LOAD_GENERIC_TABLE,

  // Task Execution Events
  BEFORE_ATTEMPT_TASK,
  AFTER_ATTEMPT_TASK,

  // Rate Limiting Events
  BEFORE_LIMIT_REQUEST_RATE,

  // Metrics Reporting Events
  BEFORE_REPORT_METRICS,
  AFTER_REPORT_METRICS,
}
