#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

quarkus.application.name=Apache Polaris (incubating)
quarkus.banner.path=/org/apache/polaris/service/banner.txt

quarkus.config.mapping.validate-unknown=true

quarkus.container-image.build=false
quarkus.container-image.push=false
# quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=apache
quarkus.container-image.name=polaris
# quarkus.container-image.tag=latest

# multi-architecture builds require pushing to a registry
# quarkus.docker.buildx.platform=linux/amd64,linux/arm64

quarkus.http.auth.basic=false
quarkus.http.access-log.enabled=true
# quarkus.http.access-log.pattern=common
quarkus.http.enable-compression=true
quarkus.http.enable-decompression=true
quarkus.http.body.handle-file-uploads=false
quarkus.http.limits.max-body-size=10240K
quarkus.http.compress-media-types=application/json,text/html,text/plain

quarkus.http.cors.origins=http://localhost:8080
quarkus.http.cors.methods=PATCH, POST, DELETE, GET, PUT
quarkus.http.cors.headers=*
quarkus.http.cors.exposed-headers=*
quarkus.http.cors.access-control-max-age=PT10M
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.port=8181
quarkus.http.test-port=0

quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.level=ALL
quarkus.log.console.json=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] [%X{requestId},%X{realmId}] [%X{traceId},%X{parentId},%X{spanId},%X{sampled}] (%t) %s%e%n
quarkus.log.file.enable=true
quarkus.log.file.level=ALL
quarkus.log.file.json=false
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] [%X{requestId},%X{realmId}] [%X{traceId},%X{parentId},%X{spanId},%X{sampled}] (%t) %s%e%n
quarkus.log.file.path=./logs/polaris.log
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd.gz
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=14
quarkus.log.category."org.apache.polaris".level=INFO
quarkus.log.category."org.apache.iceberg.rest".level=INFO
quarkus.log.category."io.smallrye.config".level=INFO

quarkus.management.enabled=true
quarkus.management.port=8182
quarkus.management.test-port=0

quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

quarkus.otel.enabled=true
quarkus.otel.sdk.disabled=false
# quarkus.otel.exporter.otlp.endpoint=http://otlp-collector:4317
# quarkus.otel.resource.attributes=deployment.environment=dev
# quarkus.otel.service.name=polaris
# quarkus.otel.traces.sampler=parentbased_always_on
# quarkus.otel.traces.sampler.arg=1.0d

polaris.context.realm-context-resolver.default-realm=default-realm
polaris.context.realm-context-resolver.type=default

polaris.config.defaults.ENFORCE_PRINCIPAL_CREDENTIAL_ROTATION_REQUIRED_CHECKING=false
polaris.config.defaults.SUPPORTED_CATALOG_STORAGE_TYPES=["S3","GCS","AZURE","FILE"]
# realm overrides
# polaris.config.realm-overrides."my-realm".INITIALIZE_DEFAULT_CATALOG_FILEIO_FOR_TEST=true
# polaris.config.realm-overrides."my-realm".SKIP_CREDENTIAL_SUBSCOPING_INDIRECTION=true

polaris.persistence.metastore-manager.type=in-memory

polaris.io.file-io-factory.type=default

polaris.log.request-id-header-name=request_id
# polaris.log.mdc.aid=polaris
# polaris.log.mdc.sid=polaris-service

polaris.metrics.tags.application=Polaris
# polaris.metrics.tags.service=polaris
# polaris.metrics.tags.environment=prod
# polaris.metrics.tags.region=us-west-2

# polaris.otel.span-attributes.service=polaris
# polaris.otel.span-attributes.environment=prod
# polaris.otel.span-attributes.region=us-west-2

# polaris.tasks.max-concurrent-tasks=100
# polaris.tasks.max-queued-tasks=1000

polaris.rate-limiter.type=default
polaris.rate-limiter.token-bucket.type=default
polaris.rate-limiter.token-bucket.requests-per-second=9999
polaris.rate-limiter.token-bucket.window=PT10S

polaris.authentication.type=default
polaris.authentication.oauth2-service.type=default
polaris.authentication.token-broker-factory.type=rsa-key-pair
polaris.authentication.token-broker-factory.max-token-generation=PT1H
# polaris.authentication.token-broker-factory.symmetric-key.secret=secret
# polaris.authentication.token-broker-factory.symmetric-key.file=/tmp/symmetric.key

# If the following properties are unset, default credentials will be used
# polaris.storage.aws.awsAccessKey=accessKey
# polaris.storage.aws.awsSecretKey=secretKey
# polaris.storage.gcp.token=token
# polaris.storage.gcp.lifespan=PT1H

%test.quarkus.log.file.enable=false
%test.quarkus.log.category."org.apache.polaris".level=INFO
%test.quarkus.log.category."org.apache.iceberg.rest".level=INFO
%test.quarkus.log.category."org.apache.iceberg.rest.RESTSessionCatalog".level=ERROR
%test.quarkus.log.category."org.apache.polaris.core.persistence.PolarisMetaStoreManagerImpl".level=ERROR
%test.quarkus.log.category."org.apache.polaris.service.context.DefaultRealmContextResolver".level=ERROR
%test.quarkus.log.category."org.apache.polaris.service.catalog.PolarisCatalogHandlerWrapper".level=ERROR
%test.quarkus.log.category."org.apache.polaris.service.storage.PolarisStorageIntegrationProviderImpl".level=ERROR
%test.quarkus.http.limits.max-body-size=1000000
%test.quarkus.otel.sdk.disabled=true
%test.polaris.authentication.token-broker-factory.type=symmetric-key
%test.polaris.authentication.token-broker-factory.symmetric-key.secret=polaris
%test.polaris.config.defaults.ALLOW_EXTERNAL_CATALOG_CREDENTIAL_VENDING=false
%test.polaris.config.defaults.ALLOW_EXTERNAL_METADATA_FILE_LOCATION=false
%test.polaris.config.defaults.ALLOW_OVERLAPPING_CATALOG_URLS=true
%test.polaris.config.defaults.ALLOW_SPECIFYING_FILE_IO_IMPL=true
%test.polaris.config.defaults.ALLOW_WILDCARD_LOCATION=true
%test.polaris.config.defaults.ENFORCE_PRINCIPAL_CREDENTIAL_ROTATION_REQUIRED_CHECKING=true
%test.polaris.config.defaults.INITIALIZE_DEFAULT_CATALOG_FILEIO_FOR_TEST=true
%test.polaris.config.defaults.SKIP_CREDENTIAL_SUBSCOPING_INDIRECTION=true
%test.polaris.config.defaults.SUPPORTED_CATALOG_STORAGE_TYPES=["FILE","S3","GCS","AZURE"]
%test.polaris.context.realm-context-resolver.default-realm=POLARIS
%test.polaris.storage.aws.awsAccessKey=accessKey
%test.polaris.storage.aws.awsSecretKey=secretKey
%test.polaris.storage.gcp.token=token
%test.polaris.storage.gcp.lifespan=PT1H
