# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.set_snapshot_ref_update import SetSnapshotRefUpdate

class TestSetSnapshotRefUpdate(unittest.TestCase):
    """SetSnapshotRefUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetSnapshotRefUpdate:
        """Test SetSnapshotRefUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetSnapshotRefUpdate`
        """
        model = SetSnapshotRefUpdate()
        if include_optional:
            return SetSnapshotRefUpdate(
                action = '',
                ref_name = '',
                type = 'tag',
                snapshot_id = 56,
                max_ref_age_ms = 56,
                max_snapshot_age_ms = 56,
                min_snapshots_to_keep = 56
            )
        else:
            return SetSnapshotRefUpdate(
                ref_name = '',
                type = 'tag',
                snapshot_id = 56,
        )
        """

    def testSetSnapshotRefUpdate(self):
        """Test SetSnapshotRefUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
