# coding: utf-8

"""
    Apache Iceberg REST Catalog API

    Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.data_file import DataFile

class TestDataFile(unittest.TestCase):
    """DataFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataFile:
        """Test DataFile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataFile`
        """
        model = DataFile()
        if include_optional:
            return DataFile(
                content = '',
                column_sizes = {keys=[1, 2], values=[100, 200]},
                value_counts = {keys=[1, 2], values=[100, 200]},
                null_value_counts = {keys=[1, 2], values=[100, 200]},
                nan_value_counts = {keys=[1, 2], values=[100, 200]},
                lower_bounds = {keys=[1, 2], values=[100, test]},
                upper_bounds = {keys=[1, 2], values=[100, test]}
            )
        else:
            return DataFile(
                content = '',
        )
        """

    def testDataFile(self):
        """Test DataFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
