# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.expression import Expression

class TestExpression(unittest.TestCase):
    """Expression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Expression:
        """Test Expression
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Expression`
        """
        model = Expression()
        if include_optional:
            return Expression(
                type = '["true","false","eq","and","or","not","in","not-in","lt","lt-eq","gt","gt-eq","not-eq","starts-with","not-starts-with","is-null","not-null","is-nan","not-nan"]',
                left = None,
                right = None,
                child = None,
                term = None,
                values = [
                    None
                    ],
                value = polaris.catalog.models.value.value()
            )
        else:
            return Expression(
                type = '["true","false","eq","and","or","not","in","not-in","lt","lt-eq","gt","gt-eq","not-eq","starts-with","not-starts-with","is-null","not-null","is-nan","not-nan"]',
                left = None,
                right = None,
                child = None,
                term = None,
                values = [
                    None
                    ],
                value = polaris.catalog.models.value.value(),
        )
        """

    def testExpression(self):
        """Test Expression"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
