#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.api.generic_table_api import GenericTableAPI


class TestGenericTableAPI(unittest.TestCase):
    """GenericTableAPI unit test stubs"""

    def setUp(self) -> None:
        self.api = GenericTableAPI()

    def tearDown(self) -> None:
        pass

    def test_create_generic_table(self) -> None:
        """Test case for create_generic_table

        Create a generic table under the given namespace
        """
        pass

    def test_drop_generic_table(self) -> None:
        """Test case for drop_generic_table

        Drop a generic table under the given namespace from the catalog
        """
        pass

    def test_list_generic_tables(self) -> None:
        """Test case for list_generic_tables

        List all generic tables identifiers underneath a given namespace
        """
        pass

    def test_load_generic_table(self) -> None:
        """Test case for load_generic_table

        Load a generic table under the given namespace from the catalog
        """
        pass


if __name__ == '__main__':
    unittest.main()
