# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.add_schema_update import AddSchemaUpdate

class TestAddSchemaUpdate(unittest.TestCase):
    """AddSchemaUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddSchemaUpdate:
        """Test AddSchemaUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddSchemaUpdate`
        """
        model = AddSchemaUpdate()
        if include_optional:
            return AddSchemaUpdate(
                action = '',
                var_schema = None,
                last_column_id = 56
            )
        else:
            return AddSchemaUpdate(
                var_schema = None,
        )
        """

    def testAddSchemaUpdate(self):
        """Test AddSchemaUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
