# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.view_history_entry import ViewHistoryEntry

class TestViewHistoryEntry(unittest.TestCase):
    """ViewHistoryEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewHistoryEntry:
        """Test ViewHistoryEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewHistoryEntry`
        """
        model = ViewHistoryEntry()
        if include_optional:
            return ViewHistoryEntry(
                version_id = 56,
                timestamp_ms = 56
            )
        else:
            return ViewHistoryEntry(
                version_id = 56,
                timestamp_ms = 56,
        )
        """

    def testViewHistoryEntry(self):
        """Test ViewHistoryEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
