# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.list_tables_response import ListTablesResponse

class TestListTablesResponse(unittest.TestCase):
    """ListTablesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTablesResponse:
        """Test ListTablesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTablesResponse`
        """
        model = ListTablesResponse()
        if include_optional:
            return ListTablesResponse(
                next_page_token = '',
                identifiers = [
                    polaris.catalog.models.table_identifier.TableIdentifier(
                        namespace = ["accounting","tax"], 
                        name = '', )
                    ]
            )
        else:
            return ListTablesResponse(
        )
        """

    def testListTablesResponse(self):
        """Test ListTablesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
