# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.notification_type import NotificationType

class TestNotificationType(unittest.TestCase):
    """NotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationType(self):
        """Test NotificationType"""
        # inst = NotificationType()

if __name__ == '__main__':
    unittest.main()
