# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.set_statistics_update import SetStatisticsUpdate

class TestSetStatisticsUpdate(unittest.TestCase):
    """SetStatisticsUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetStatisticsUpdate:
        """Test SetStatisticsUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetStatisticsUpdate`
        """
        model = SetStatisticsUpdate()
        if include_optional:
            return SetStatisticsUpdate(
                action = '',
                snapshot_id = 56,
                statistics = polaris.catalog.models.statistics_file.StatisticsFile(
                    snapshot_id = 56, 
                    statistics_path = '', 
                    file_size_in_bytes = 56, 
                    file_footer_size_in_bytes = 56, 
                    blob_metadata = [
                        polaris.catalog.models.blob_metadata.BlobMetadata(
                            type = '', 
                            snapshot_id = 56, 
                            sequence_number = 56, 
                            fields = [
                                56
                                ], 
                            properties = {
                                'key' : ''
                                }, )
                        ], )
            )
        else:
            return SetStatisticsUpdate(
                statistics = polaris.catalog.models.statistics_file.StatisticsFile(
                    snapshot_id = 56, 
                    statistics_path = '', 
                    file_size_in_bytes = 56, 
                    file_footer_size_in_bytes = 56, 
                    blob_metadata = [
                        polaris.catalog.models.blob_metadata.BlobMetadata(
                            type = '', 
                            snapshot_id = 56, 
                            sequence_number = 56, 
                            fields = [
                                56
                                ], 
                            properties = {
                                'key' : ''
                                }, )
                        ], ),
        )
        """

    def testSetStatisticsUpdate(self):
        """Test SetStatisticsUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
