# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.add_view_version_update import AddViewVersionUpdate

class TestAddViewVersionUpdate(unittest.TestCase):
    """AddViewVersionUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddViewVersionUpdate:
        """Test AddViewVersionUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddViewVersionUpdate`
        """
        model = AddViewVersionUpdate()
        if include_optional:
            return AddViewVersionUpdate(
                action = '',
                view_version = polaris.catalog.models.view_version.ViewVersion(
                    version_id = 56, 
                    timestamp_ms = 56, 
                    schema_id = 56, 
                    summary = {
                        'key' : ''
                        }, 
                    representations = [
                        null
                        ], 
                    default_catalog = '', 
                    default_namespace = ["accounting","tax"], )
            )
        else:
            return AddViewVersionUpdate(
                view_version = polaris.catalog.models.view_version.ViewVersion(
                    version_id = 56, 
                    timestamp_ms = 56, 
                    schema_id = 56, 
                    summary = {
                        'key' : ''
                        }, 
                    representations = [
                        null
                        ], 
                    default_catalog = '', 
                    default_namespace = ["accounting","tax"], ),
        )
        """

    def testAddViewVersionUpdate(self):
        """Test AddViewVersionUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
