# coding: utf-8

"""
    Polaris Management Service

    Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.management.models.view_privilege import ViewPrivilege

class TestViewPrivilege(unittest.TestCase):
    """ViewPrivilege unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testViewPrivilege(self):
        """Test ViewPrivilege"""
        # inst = ViewPrivilege()

if __name__ == '__main__':
    unittest.main()
