#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# coding: utf-8

"""
    Polaris Management Service

    Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.management.api.polaris_default_api import PolarisDefaultApi


class TestPolarisDefaultApi(unittest.TestCase):
    """PolarisDefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolarisDefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_grant_to_catalog_role(self) -> None:
        """Test case for add_grant_to_catalog_role

        """
        pass

    def test_assign_catalog_role_to_principal_role(self) -> None:
        """Test case for assign_catalog_role_to_principal_role

        """
        pass

    def test_assign_principal_role(self) -> None:
        """Test case for assign_principal_role

        """
        pass

    def test_create_catalog(self) -> None:
        """Test case for create_catalog

        """
        pass

    def test_create_catalog_role(self) -> None:
        """Test case for create_catalog_role

        """
        pass

    def test_create_principal(self) -> None:
        """Test case for create_principal

        """
        pass

    def test_create_principal_role(self) -> None:
        """Test case for create_principal_role

        """
        pass

    def test_delete_catalog(self) -> None:
        """Test case for delete_catalog

        """
        pass

    def test_delete_catalog_role(self) -> None:
        """Test case for delete_catalog_role

        """
        pass

    def test_delete_principal(self) -> None:
        """Test case for delete_principal

        """
        pass

    def test_delete_principal_role(self) -> None:
        """Test case for delete_principal_role

        """
        pass

    def test_get_catalog(self) -> None:
        """Test case for get_catalog

        """
        pass

    def test_get_catalog_role(self) -> None:
        """Test case for get_catalog_role

        """
        pass

    def test_get_principal(self) -> None:
        """Test case for get_principal

        """
        pass

    def test_get_principal_role(self) -> None:
        """Test case for get_principal_role

        """
        pass

    def test_list_assignee_principal_roles_for_catalog_role(self) -> None:
        """Test case for list_assignee_principal_roles_for_catalog_role

        """
        pass

    def test_list_assignee_principals_for_principal_role(self) -> None:
        """Test case for list_assignee_principals_for_principal_role

        """
        pass

    def test_list_catalog_roles(self) -> None:
        """Test case for list_catalog_roles

        """
        pass

    def test_list_catalog_roles_for_principal_role(self) -> None:
        """Test case for list_catalog_roles_for_principal_role

        """
        pass

    def test_list_catalogs(self) -> None:
        """Test case for list_catalogs

        """
        pass

    def test_list_grants_for_catalog_role(self) -> None:
        """Test case for list_grants_for_catalog_role

        """
        pass

    def test_list_principal_roles(self) -> None:
        """Test case for list_principal_roles

        """
        pass

    def test_list_principal_roles_assigned(self) -> None:
        """Test case for list_principal_roles_assigned

        """
        pass

    def test_list_principals(self) -> None:
        """Test case for list_principals

        """
        pass

    def test_revoke_catalog_role_from_principal_role(self) -> None:
        """Test case for revoke_catalog_role_from_principal_role

        """
        pass

    def test_revoke_grant_from_catalog_role(self) -> None:
        """Test case for revoke_grant_from_catalog_role

        """
        pass

    def test_revoke_principal_role(self) -> None:
        """Test case for revoke_principal_role

        """
        pass

    def test_rotate_credentials(self) -> None:
        """Test case for rotate_credentials

        """
        pass

    def test_update_catalog(self) -> None:
        """Test case for update_catalog

        """
        pass

    def test_update_catalog_role(self) -> None:
        """Test case for update_catalog_role

        """
        pass

    def test_update_principal(self) -> None:
        """Test case for update_principal

        """
        pass

    def test_update_principal_role(self) -> None:
        """Test case for update_principal_role

        """
        pass


if __name__ == '__main__':
    unittest.main()
