#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

services:
  cockroachdb:
    image: cockroachdb/cockroach:v26.2.3
    command: start-single-node --insecure
    ports:
      - "26257:26257"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    healthcheck:
      test: "curl --fail http://localhost:8080/health?ready=1"
      interval: 5s
      timeout: 2s
      retries: 15
  cockroachdb-init:
    image: cockroachdb/cockroach:v26.2.3
    depends_on:
      cockroachdb:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c", "cockroach sql --insecure --host=cockroachdb -e 'CREATE DATABASE IF NOT EXISTS polaris;'"]
  polaris-bootstrap:
    depends_on:
      cockroachdb-init:
        condition: service_completed_successfully
  polaris:
    depends_on:
      cockroachdb-init:
        condition: service_completed_successfully
