# coding: utf-8

"""
    Apache Iceberg REST Catalog API

    Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.sort_direction import SortDirection

class TestSortDirection(unittest.TestCase):
    """SortDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortDirection(self):
        """Test SortDirection"""
        # inst = SortDirection()

if __name__ == '__main__':
    unittest.main()
