# coding: utf-8

"""
    Apache Iceberg REST Catalog API

    Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.content_file import ContentFile

class TestContentFile(unittest.TestCase):
    """ContentFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentFile:
        """Test ContentFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentFile`
        """
        model = ContentFile()
        if include_optional:
            return ContentFile(
                content = '',
                file_path = '',
                file_format = 'avro',
                spec_id = 56,
                partition = [1,"bar"],
                file_size_in_bytes = 56,
                record_count = 56,
                key_metadata = '78797A',
                split_offsets = [
                    56
                    ],
                sort_order_id = 56
            )
        else:
            return ContentFile(
                content = '',
                file_path = '',
                file_format = 'avro',
                spec_id = 56,
                file_size_in_bytes = 56,
                record_count = 56,
        )
        """

    def testContentFile(self):
        """Test ContentFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
