# coding: utf-8

"""
    Apache Iceberg REST Catalog API

    Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.create_namespace_response import CreateNamespaceResponse

class TestCreateNamespaceResponse(unittest.TestCase):
    """CreateNamespaceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNamespaceResponse:
        """Test CreateNamespaceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNamespaceResponse`
        """
        model = CreateNamespaceResponse()
        if include_optional:
            return CreateNamespaceResponse(
                namespace = ["accounting","tax"],
                properties = {"owner":"Ralph","created_at":"1452120468"}
            )
        else:
            return CreateNamespaceResponse(
                namespace = ["accounting","tax"],
        )
        """

    def testCreateNamespaceResponse(self):
        """Test CreateNamespaceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
