# coding: utf-8

"""
    Apache Iceberg REST Catalog API

    Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.add_sort_order_update import AddSortOrderUpdate

class TestAddSortOrderUpdate(unittest.TestCase):
    """AddSortOrderUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddSortOrderUpdate:
        """Test AddSortOrderUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddSortOrderUpdate`
        """
        model = AddSortOrderUpdate()
        if include_optional:
            return AddSortOrderUpdate(
                action = 'add-sort-order',
                sort_order = polaris.catalog.models.sort_order.SortOrder(
                    order_id = 56, 
                    fields = [
                        polaris.catalog.models.sort_field.SortField(
                            source_id = 56, 
                            transform = '["identity","year","month","day","hour","bucket[256]","truncate[16]"]', 
                            direction = 'asc', 
                            null_order = 'nulls-first', )
                        ], )
            )
        else:
            return AddSortOrderUpdate(
                action = 'add-sort-order',
                sort_order = polaris.catalog.models.sort_order.SortOrder(
                    order_id = 56, 
                    fields = [
                        polaris.catalog.models.sort_field.SortField(
                            source_id = 56, 
                            transform = '["identity","year","month","day","hour","bucket[256]","truncate[16]"]', 
                            direction = 'asc', 
                            null_order = 'nulls-first', )
                        ], ),
        )
        """

    def testAddSortOrderUpdate(self):
        """Test AddSortOrderUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
