/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.polaris.persistence.relational.jdbc;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.UUID;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcConnectionPool;
import org.junit.jupiter.api.Test;

/**
 * End-to-end tests against a real H2 database showing that the persistence code is agnostic of the
 * database schema: the schema is created and selected entirely through the datasource (here via
 * H2's {@code INIT=} URL setting, the equivalent of the PostgreSQL driver's {@code currentSchema}
 * connection property plus a DBA-created schema), and the unqualified SQL generated by the
 * persistence layer resolves against it.
 */
class DatasourceOperationsSchemaTest {

  private static DataSource createDataSource(String schemaName) {
    String url = "jdbc:h2:mem:schema_test_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1";
    if (schemaName != null) {
      url += ";INIT=CREATE SCHEMA IF NOT EXISTS " + schemaName + "\\;SET SCHEMA " + schemaName;
    }
    return JdbcConnectionPool.create(url, "sa", "");
  }

  /**
   * Loads the script a fresh bootstrap would actually run, so that a schema version bump keeps
   * exercising the invariant that the latest bootstrap path selects no schema of its own.
   */
  private static InputStream openSchemaScript() {
    return DatabaseType.H2.openInitScriptResource(DatabaseType.H2.getLatestSchemaVersion());
  }

  /** The schema holding the ENTITIES table, as reported by the database catalog. */
  private static String schemaContainingEntitiesTable(DataSource dataSource) throws SQLException {
    try (Connection connection = dataSource.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(
                "SELECT table_schema FROM information_schema.tables WHERE table_name = 'ENTITIES' LIMIT 1")) {
      try (ResultSet resultSet = statement.executeQuery()) {
        return resultSet.next() ? resultSet.getString(1) : null;
      }
    }
  }

  @Test
  void bootstrapsIntoDatasourceConfiguredSchema() throws SQLException {
    DataSource dataSource = createDataSource("custom_polaris");
    DatasourceOperations ops =
        new DatasourceOperations(
            dataSource, SimpleRelationalJdbcConfiguration.forDatabaseType(DatabaseType.H2));

    assertThat(JdbcBasePersistenceImpl.entityTableExists(ops)).isFalse();

    ops.executeScript(openSchemaScript());

    // Unqualified queries resolve against the schema selected by the datasource.
    assertThat(JdbcBasePersistenceImpl.loadSchemaVersion(ops, false))
        .isEqualTo(DatabaseType.H2.getLatestSchemaVersion());
    // H2 case-folds the unquoted identifier to uppercase.
    assertThat(schemaContainingEntitiesTable(dataSource)).isEqualTo("CUSTOM_POLARIS");
  }

  @Test
  void bootstrapsIntoDatabaseDefaultSchemaWhenDatasourceSelectsNone() throws SQLException {
    DataSource dataSource = createDataSource(null);
    DatasourceOperations ops =
        new DatasourceOperations(
            dataSource, SimpleRelationalJdbcConfiguration.forDatabaseType(DatabaseType.H2));

    assertThat(JdbcBasePersistenceImpl.entityTableExists(ops)).isFalse();

    ops.executeScript(openSchemaScript());

    assertThat(JdbcBasePersistenceImpl.loadSchemaVersion(ops, false))
        .isEqualTo(DatabaseType.H2.getLatestSchemaVersion());
    // Without a datasource-selected schema, tables land in the database's default schema.
    assertThat(schemaContainingEntitiesTable(dataSource)).isEqualTo("PUBLIC");
  }
}
