/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.polaris.tasks.api;

/**
 * User-facing task submission API.
 *
 * <p>This interface intentionally only provides a function to submit tasks.
 */
public interface Tasks {
  /**
   * Submits the given task request for execution.
   *
   * <p>This API only guarantees that, upon successful return from this method, the task request
   * will eventually be executed. The exact timing and location (i.e., which system process) of the
   * task execution depends on configuration specifics and task state.
   *
   * <p>Task executions are uniquely identified by their {@link TaskId}, which are generated by the
   * task behavior implementation. Task behavior implementations produce either new, unique task IDs
   * per submission or deterministic task IDs based on the task parameters.
   *
   * <p>Task behavior implementations may request an initial delay of a task execution and also
   * define optional retry behaviors for successful and failed executions.
   *
   * <p>Once this function returns successfully, the task execution request is durably persisted.
   *
   * <p>Implementations provide a best-effort approach, offering at-least-once semantics.
   *
   * <p>This API provides no guarantee when a task will be executed. Implementations may defer
   * execution to any point in time in the future.
   *
   * <p>This API offers no task priorities. When tasks are executed is determined by the
   * implementation.
   *
   * @param <PARAM> task input parameter type
   * @param <RESULT> task execution result type
   * @param behaviorId ID of task behavior being submitted. An {@link IllegalArgumentException} is
   *     thrown if no behavior for this ID is registered.
   * @param realmId realm ID for which the task is submitted
   * @param param task parameter value. Task behavior implementations derive the actual task ID
   *     based on their implementation and potentially from this task parameter value. The caller is
   *     responsible for providing a correct, compatible parameter value for the given task
   *     behavior.
   * @param resultType type of the result value object. The caller is responsible for providing the
   *     correct, compatible result type for the given task behavior.
   * @return the task submission handle containing the task ID
   */
  <PARAM extends TaskParameter, RESULT extends TaskResult> TaskSubmission<RESULT> submit(
      TaskBehaviorId behaviorId, String realmId, PARAM param, Class<RESULT> resultType);
}
