#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Build and Stage Helm Chart

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (check to enable, uncheck to perform actual operations)'
        required: false
        type: boolean
        default: true
  workflow_run:
    workflows: ["Build and Publish Docker Images"]
    types:
      - completed

jobs:
  build-and-stage-helm-chart:
    name: Build and Stage Helm Chart
    runs-on: ubuntu-latest
    # Only run if manually triggered or if Docker workflow succeeded
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: read
    outputs:
      dry_run: ${{ steps.set-outputs.outputs.dry_run }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set DRY_RUN environment variable
        id: set-outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual trigger - use input parameter
            if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
              echo "DRY_RUN=1" >> $GITHUB_ENV
              echo "dry_run=1" >> $GITHUB_OUTPUT
              echo "DRY_RUN mode enabled - no actual changes will be made"
            else
              echo "DRY_RUN=0" >> $GITHUB_ENV
              echo "dry_run=0" >> $GITHUB_OUTPUT
              echo "DRY_RUN mode disabled - actual changes will be made"
            fi
          else
            # Automatic trigger - get upstream workflow's dry_run value
            workflow_run_id="${{ github.event.workflow_run.id }}"
            
            # Fetch the jobs for the workflow run
            jobs_response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${workflow_run_id}/jobs")
            
            # Extract the dry_run output from the build-and-publish-docker job
            upstream_dry_run=$(echo "$jobs_response" | jq -r '.jobs[] | select(.name == "Build and Publish Docker Images") | .outputs.dry_run // "0"')
            
            echo "DRY_RUN=${upstream_dry_run}" >> $GITHUB_ENV
            echo "dry_run=${upstream_dry_run}" >> $GITHUB_OUTPUT
            echo "Retrieved upstream dry_run value: ${upstream_dry_run}"
          fi

      - name: Validate release candidate tag
        run: |
          releasey_dir="$(pwd)/releasey"
          LIBS_DIR="${releasey_dir}/libs"

          source "${LIBS_DIR}/_log.sh"
          source "${LIBS_DIR}/_constants.sh"
          source "${LIBS_DIR}/_version.sh"

          print_info "Determining version from current git tag..."

          if ! git_tag=$(git describe --tags --exact-match HEAD 2>/dev/null); then
            print_error "Current HEAD is not on a release candidate tag. Please checkout a release candidate tag first."
            exit 1
          fi
          print_info "Found git tag: ${git_tag}"

          # Validate git tag format and extract version components
          if ! validate_and_extract_git_tag_version "${git_tag}"; then
            print_error "Invalid git tag format: ${git_tag}"
            print_error "Expected format: apache-polaris-x.y.z-incubating-rcN"
            exit 1
          fi

          print_info "Validated release candidate tag: ${git_tag}"
          print_info "Version: ${version_without_rc}"
          print_info "RC number: ${rc_number}"

          # Export variables for next steps
          echo "git_tag=${git_tag}" >> $GITHUB_ENV
          echo "version_without_rc=${version_without_rc}" >> $GITHUB_ENV
          echo "rc_number=${rc_number}" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
        with:
          version: 'latest'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Import GPG key
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          gpg-connect-agent reloadagent /bye

          # Test that GPG can sign (this will cache the passphrase)
          echo "test" | gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --armor --detach-sign

          mkdir -p ~/.gradle
          echo "signing.gnupg.keyName=$(gpg --list-secret-keys --keyid-format LONG | grep sec | head -1 | sed 's/.*\/\([A-F0-9]*\).*/\1/')" >> ~/.gradle/gradle.properties

      - name: Create Helm package
        run: |
          releasey_dir="$(pwd)/releasey"
          LIBS_DIR="${releasey_dir}/libs"

          source "${LIBS_DIR}/_log.sh"
          source "${LIBS_DIR}/_exec.sh"
          source "${LIBS_DIR}/_gpg.sh"

          print_info "Creating Helm package..."
          exec_process cd helm
          exec_process helm package polaris
          exec_process helm gpg sign polaris-${version_without_rc}.tgz
          calculate_sha512 polaris-${version_without_rc}.tgz polaris-${version_without_rc}.tgz.sha512
          exec_process gpg --armor --output polaris-${version_without_rc}.tgz.asc --detach-sig polaris-${version_without_rc}.tgz
          calculate_sha512 polaris-${version_without_rc}.tgz.prov polaris-${version_without_rc}.tgz.prov.sha512
          exec_process gpg --armor --output polaris-${version_without_rc}.tgz.prov.asc --detach-sig polaris-${version_without_rc}.tgz.prov

          print_success "Helm package created successfully"

      - name: Stage Helm chart to Apache dist dev repository
        env:
          SVN_USERNAME: ${{ secrets.APACHE_USERNAME }}
          SVN_PASSWORD: ${{ secrets.APACHE_PASSWORD }}
        run: |
          releasey_dir="$(pwd)/releasey"
          LIBS_DIR="${releasey_dir}/libs"

          source "${LIBS_DIR}/_log.sh"
          source "${LIBS_DIR}/_constants.sh"
          source "${LIBS_DIR}/_exec.sh"

          print_info "Staging Helm chart to Apache dist dev repository..."

          dist_dev_dir=${releasey_dir}/polaris-dist-dev
          print_info "Checking out ${APACHE_DIST_URL}${APACHE_DIST_PATH} to ${dist_dev_dir}..."
          exec_process svn checkout --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive "${APACHE_DIST_URL}${APACHE_DIST_PATH}" "${dist_dev_dir}"

          print_info "Copying Helm package files..."
          exec_process mkdir -p "${dist_dev_dir}/helm-chart/${version_without_rc}"
          exec_process cp helm/polaris-${version_without_rc}.tgz* "${dist_dev_dir}/helm-chart/${version_without_rc}/"

          print_info "Updating Helm index..."
          exec_process cd "${dist_dev_dir}/helm-chart"
          exec_process helm repo index .

          print_info "Adding files to SVN..."
          cd "${dist_dev_dir}"
          exec_process svn add index.yaml
          exec_process svn add "helm-chart/${version_without_rc}"

          print_info "Committing changes..."
          exec_process svn commit --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive -m "Stage Apache Polaris Helm chart ${version_without_rc} RC${rc_number}"

          print_success "Helm chart staged to Apache dist dev repository successfully"