#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Regression Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  regtest:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions
        run: mkdir -p regtests/output && chmod 777 regtests/output && chmod 777 regtests/t_*/ref/*

      - name: Print Podman info
        run: |
          podman -v
          podman machine info
          minikube podman-env

      - name: Image build
        run: |
          BUILD_TAG=helm-ci-$(date +%s)
          echo BUILD_TAG=${BUILD_TAG} >> ${GITHUB_ENV}
          ./gradlew :polaris-quarkus-service:build -x check \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.tag=${BUILD_TAG} \
            -PeclipseLinkDeps=com.h2database:h2:2.3.232

      - name: Regression Test
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          cd regtests
          # create compose override file and set image tag
          cat <<EOF > docker-compose.override.yml
          services:
            polaris:
              image: apache/polaris:${BUILD_TAG}
          EOF
          podman compose up --build --exit-code-from regtest